### ISSUE TITLE
SCALE 13x pages show SCALE title

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#119]
When we launched the SCALE 14x site it looks like the 13x pages were updated as well. Can we fix?

**Comment by rgolan** [comment]
Could you explain more what on the pages was updated.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
Actually looks like the logo issue was fixed a bit back.  Its just the title tag now.  Not a big deal but its causing scale 13x pages to show up as scale 14x in search results.

**Comment by rgolan** [comment]
I don’t understand what you mean by title tag. Could you give me a URL of a page with this issue? I’m looking at

https://www.socallinuxexpo.org/scale/13x/sponsor/hp-1 <https://www.socallinuxexpo.org/scale/13x/sponsor/hp-1>

as an example and I don’t see it.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by rgolan** [comment]
I get what you’re saying now. I’ll look into fixing that. Drupal puts the site name in the title by default. I can probably fix that but it’ll take me a little while.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
![2015-06-17_2251](https://cloud.githubusercontent.com/assets/289654/8224950/71000f36-1543-11e5-9f5f-dc1d62301a7c.png)
![2015-06-17_2249](https://cloud.githubusercontent.com/assets/289654/8224949/70ff50f0-1543-11e5-97fe-257b0d81468c.png)

**Comment by irabinovitch** [comment]
NVM sounds like you got it.  Thanks. No rush.

**Comment by rgolan** [comment]
I fixed it for pages that are getting the 13x theme. Speaker pages will always show on the current theme since we reuse those nodes.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
Heres an example of the pages I was seeing with the 14x logo:

https://www.socallinuxexpo.org/scale/13x/speakers/andrew-kirch

**Comment by rgolan** [comment]
The problem here is that we keep users (speakers) from year to year and each user has only one user profile page. Give that, I think we decided to show those pages with the current theme and show only presentations from the current year. I'm open to suggestions on changing this.

**Comment by irabinovitch** [comment]
I was thinking we could year part of the url for the theme, but will defer to you.

**Comment by rgolan** [comment]
I'm not clear on what you're suggesting. Please elaborate.

**Comment by irabinovitch** [comment]
Looks like we're having this issue for SCALE 14x content now. Both SCALE 13x and SCALE 14x pages now show SCALE 15x in the title.  

My question is can  we dynamically generate the title based on the URL (eg if its /scale14x/ it should show SCALE 14x in the title). Otherwise should we start staticing the old sites again?

**Comment by rgolan** [comment]
I'm pretty sure I can make it act like 13x did when 14x was current. Are you sure the 13x pages, other than user pages, are showing the 15x head title?

**Comment by irabinovitch** [comment]
Looks like its just user pages again.

**Comment by rgolan** [comment]
I modified the 14x theme to fix the head titles. It should be good now. Please review.

**Comment by irabinovitch** [comment]
Working as expected now. Thanks!
