### ISSUE TITLE
Publish Policy regarding SCALE passes for Kids

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#188]
During the SCALE Chairs meeting we agreed that kids under 18 will receive a free pass to scale, if they are attending with an adult.  Lets update our registration pages sand policies to include this information.

**Comment by irabinovitch** [comment]
@leizleiz did we publish anything?

**Comment by leizleiz** [comment]
I did on the registration page. Let me know if it needs changing.
