### ISSUE TITLE
Recruit volunteer to focus on keynote planning / coordination

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#189]
Planning for the SCALE keynotes on Saturday and Sunday has become a large time investment.  As per the SCALE Chairs meeting, Shyam has taken on an action item of recruiting someone to lead and coordinate keynote related content.

**Comment by irabinovitch** [comment]
@shyamkapadia any luck on this one? you said you had someone in mind?

**Comment by irabinovitch** [comment]
@shyamkapadia Did we find someone for this?

**Comment by shyamkapadia** [comment]
@irabinovitch: Yes Matti is looking into this..

**Comment by irabinovitch** [comment]
Great. Closing. Thanks.
