### ISSUE TITLE
Announce Call For Papers

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#190]
We would like to announce our call for papers in May. It will open sometime around May 16th, and close the last Friday in October. This ticket will track any changes to the CFP text, and the announcement process.

**Comment by rgolan** [comment]
I've pushed changes to the production site to allow creation of new 15x presentations. Should I disable it now for the Speaker role. It would be good to do a little testing.

**Comment by irabinovitch** [comment]
We've announced on social media. Pending task is to announce on scale-announce.

@lcafiero Can we find sometime this week to 1) test phplist works properly post migration 2) agree on text?

**Comment by irabinovitch** [comment]
@lcafiero Reminder that the CFP closes on 11/15. Can we please get an email out this weekend and mid week?

**Comment by lcafiero** [comment]
Yes. How do we test phplist works properly other than just making it work
(I've already sent out one message earlier this year, got the usual number
of bounces).

**Comment by irabinovitch** [comment]
@lcafiero We should be all set at this point.

**Comment by lcafiero** [comment]
OK. Sending out an announcement tonight and midweek.
