### ISSUE TITLE
Migrate Systems from ActUSA

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#194]
ActUSA's sponsorship of SCALE related infrastructure will end on June 30th.  After this date a monthly fee will apply.

This ticket is to track the work needed to move the following SCALE systems from ActUSA to an alternate provider:

- [x] Email
- [x] Mailing Lists 
- [x] SCALE website
- [x] LinuxFests.org website
- [x] registration systems
- [x] VOIP Services
- [ ] Wiki

LinuxFests will handle transfer of the following systems elsewhere:
- TXLF / DevOps reg systems
- linuxfests.org web and email

A full inventory of systems is available at:
https://docs.google.com/spreadsheets/d/1uoLkaLXzBVGZQXbPI5n8Q52hulhI2B9JaDUATn7sEDM/edit#gid=0

**Comment by irabinovitch** [comment]
@jhoblitt  and @hriday and Ev met with Stu today and got some brain dumps.  @jhoblitt is currently conducting discovery on what is running on the servers.

**Comment by irabinovitch** [comment]
Lei has given the go ahead to shutdown SCALEreg. We just need to give him a VM where ever we end up, ideally before June 1st so he can launch registration for SCALE 15x.

**Comment by irabinovitch** [comment]
Email migration to Google Apps/GMAIL was completed over the weekend.

**Comment by irabinovitch** [comment]
Took an initial stab at migrating our wiki content to github's wiki system at https://github.com/socallinuxexpo/scale-wiki/wiki 

Links between pages and some of the formatting are broken, but is probably enough for the historical data/background we need, and we can start fresh either here on github or elsewhere..

**Comment by lcafiero** [comment]
As far as the mailing list is concerned, I don't mind wrangling with PHPList if there are no FOSS alternatives. I think it's important that if we do have a mailing list, it should be FOSS-based -- walking the walk as we talk the talk. 

That said, if we stay with PHPList, I should mention that my knowledge of PHPList is rudimentary at best -- I can send emails, monitor and amend bounces where necessary, add and delete emails, and download backups as csv files (which I have done). As far as migrating PHPList to another server, I'm at a loss and would defer to someone with more experience.

**Comment by irabinovitch** [comment]
All systems are now considered migrated as ActUSA has shut down our systems.
