### ISSUE TITLE
Document Existing SCALE Hosted Infrastructure

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#197]
Arrange for a meeting either online or in person between 2-3 SCALE-Tech members and Stu Sheldon to review and document the existing Web/Email/VoIP infrastructure.

Requirements:
- At least 2 current members of the tech team should be present. 
- All notes should be published either in the SCALE wiki or another public platform.
- Configurations, scripts, tools, etc should be checked into source control.

Optional:
- Record/post the meeting online.

**Comment by irabinovitch** [comment]
@jhoblitt  and @hriday had this meeting with Stu and Ev today.  I dont believe we got a recording, but notes were sent to tech@

**Comment by irabinovitch** [comment]
@hriday  @jhoblitt are we comfortable calling this closed at this point?

**Comment by jhoblitt** [comment]
Are we going to consider the google sheets migration notes the official production documentation?

**Comment by irabinovitch** [comment]
Of the legacy environment sure.  Of the new stuff, it looks like docs are going along side the code to build it.
