### ISSUE TITLE
Document SCALE onsite network at Pasadena Convention Center

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#198]
Arrange for a meeting either online or in person between 2-3 SCALE-Tech members and Stu Sheldon to review and document the SCALE network infrastructure and configuration.

Requirements:
- At least 2 current members of the tech team should be present.
- All notes should be published either in the SCALE wiki or another public platform.
- Any configurations, scripts, tools, etc received should be checked into source control.

Optional:
- Record/post the meeting online.

**Comment by irabinovitch** [comment]
@hriday Did we get any notes during the meeting with Stu?

**Comment by hriday** [comment]
Regarding the on site router configs, Stu says that it was all dynamic, and
there's no backup. We probably can get some physical layer diagrams, but
the show floor will have to be redesigned from scratch.
