### ISSUE TITLE
Decide on User Auth 

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#202]
Hi @rgolan,

As part of #194  we're trying to identify what needs to be migrated to our new hosting provider when the time comes.  At the moment Drupal appears to use LDAP to authenticate some users, and local auth for others.

LDAP today is used for mail, wiki, and drupal.  Mail is moving to gmail and no longe requires ldap.  Wiki is TBD but can likely adapt to whatever we choose for Drupal, etc. 

With that in mind. Do you have any preferences on what we should use here for centralized authentication?   Drupal looks to have a Google Auth and OAUTH modules. Do you have any experience with those?   Having a single login to all thing is nice, but not required.

Ilan

CC: @hriday @jhoblitt

**Comment by jhoblitt** [comment]
Re: wikis.  I am actually a fan of using https://github.com/gollum/gollum in a git repo.  This is what github's per repo wikis are built on and it also (or did as of a couple of years ago) works with bitbucket's wikis.  Gollum can be started as a http server on the loopback address without any external setup and even has reasonable search functionality. 

I have not looked at what a migration would entail but moving to a GH wiki would eliminate another ldap dependency.

**Comment by irabinovitch** [comment]
We didn't migrate LDAP.  So far I think everything but drupal is authenticating against Google Auth.  Anything else we want to do here?
