### ISSUE TITLE
DNS migration

### ISSUE THREAD

**Issue by jhoblitt** [socallinuxexpo/SCALE-Planning#203]
Needs to be relocated away from Actusa servers. @irabinovitch appears to control the domain and presumably can change the SOA servers.  The current interum plan is to import the bind zone files directly into route53.

**Comment by irabinovitch** [comment]
Josh pushed up our DNS zones to route53. You can find details in https://github.com/socallinuxexpo/scale-dns

We've cutover socallinuxexpo.com/net and linuxfests.com/net without issue so far.   We will leave .org for migration this weekend.

**Comment by irabinovitch** [comment]
DNS migration is complete. All domains are on Route53 for primary DNS now.
