### ISSUE TITLE
Migrate scale-announce

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#205]
SCALE-Announce is currently powered by PHPList and runs on mail.linuxfests.org which run on ActUSA infrastructure.  As part of #194 we need to move this as well.  @lcafiero  has mentioned not being a fan of the UX/UI for PHPList and asked if there are other tools we can consider.

SCALE-Announce previously was powered by mailman.  Due to the size of the list mailman was choking on announcements.   It also doesn't have reporting on email delivery / bounce rates and other features that are nice to have for announcements.

This ticket is to track:
- [x] backing up PHPList
- [x] Evaluating alternative solutions
- [x] Setting up announcements on our new hosting provider. Either PHPList or something new.

Once complete don't forget to:
- [ ] Update subscription links on the website
- [ ] Update SCALEReg to send opt-in subscriptions to new system.

CC: @jhoblitt @lcafiero @hriday

**Comment by irabinovitch** [comment]
Other LinuxFests events are presently using various hosted services, but these are not open source:

- MadMimi (donated to TXLF)
- MailChimp (paid for by DevOpsDays SV)

**Comment by jhoblitt** [comment]
I think relying bulk email via Gapps would be asking for trouble.  See: https://support.google.com/a/answer/166852?hl=en

If we don't move to a fully managed solution, I think should seriously consider using a relying service such as https://aws.amazon.com/ses/, https://www.mailgun.com/, or http://mandrill.com/.

**Comment by irabinovitch** [comment]
Lets focus on the specific software to use.  The MTA is something we can revisit once we have this in place.

**Comment by irabinovitch** [comment]
Got 0 feedback on alternate software, so I've proceeded to migrate phplist and mailman. See the open prs in scale-chef.

**Comment by irabinovitch** [comment]
calling this done.  although its not completely done until we update the DNS for lists.linuxfests.org

**Comment by irabinovitch** [comment]
DNS updated.

**Comment by leizleiz** [comment]
Do we actually auto-subscribe attendees via some scalereg integration? I think previously we just manually added people who checked the subscribe box when registering.

**Comment by irabinovitch** [comment]
@leizleiz We previously had a cron job that would query for new registrations nightly
(eg select email from attendees where can_email=1 and date>=$LAST_EXPORT)
that would then get piped into phplist for auto subscription.
