### ISSUE TITLE
disband scale-tech github org

### ISSUE THREAD

**Issue by jhoblitt** [socallinuxexpo/SCALE-Planning#207]
Per @irabinovitch, scale is disbanding the per commitee github orgs.  The `scale-tech` owners are @socallinuxexpo-org @stu-actusa-net .

/cc @hriday @irabinovitch

**Comment by davidelang** [comment]
what is going to happen to the data currently in scale-tech?

**Comment by irabinovitch** [comment]
@davidelang What data do you believe is presently in scale-tech?

**Comment by jhoblitt** [comment]
There are 6 repos in the org.

These repos are empty:

* https://github.com/scale-tech/network-monitoring
* https://github.com/scale-tech/wireless
* https://github.com/scale-tech/scale-selfreg

This repo has only a list of the other repos:

https://github.com/scale-tech/repo-list

These two repos should be transferred to the socallinuxexpo org, if they need to be preserved:

https://github.com/scale-tech/scale-signs/
https://github.com/scale-tech/stu-tools

**Comment by irabinovitch** [comment]
stu-tools has been at https://github.com/socallinuxexpo/stu-tools since 2012. 

scale-signs was migrated to https://github.com/socallinuxexpo/scale-signs

**Comment by jhoblitt** [comment]
My vote is for summary execution.

**Comment by jaymzh** [comment]
:+1: unless @davidelang knows of something we're missing.

**Comment by davidelang** [comment]
It sounds like you have now migrated everything.

**Comment by socallinuxexpo-org** [comment]
Can you check and see if there's anything we need there?

**Comment by irabinovitch** [comment]
@socallinuxexpo-org its good to kill. Can we either delete the socallinuxexpo-org  use or transfer it to someone still with the org?

**Comment by irabinovitch** [comment]
The last repos from scale-av (big brother scripts) has been transferred to the socallinuxexpo org.
Confirmed that the remaining repos in scale-tech were either empty or stale copies of repos that are active in socallinuxexpo.  As such both scale-tech and scale-av have been deleted.
