### ISSUE TITLE
basic [external] up/down monitoring

### ISSUE THREAD

**Issue by jhoblitt** [socallinuxexpo/SCALE-Planning#210]
We desperately need basic up/down monitoring with some sort of team visibility.  I think a slack channel for notifications would be more useful then a dashboard.

Obvious, simple checks:
- icmp echo
- http status
- https status + cert validity
- key dns records
- whois info (including registration expiration)

/cc @socallinuxexpo/infra

**Comment by irabinovitch** [comment]
New Relic has donated a synthetics account for our use.  Datadog has done the  same for infra monitoring

**Comment by irabinovitch** [comment]
We're monitoring the following now:
* http and https status are both being monitored by Datadog and New Relic Synthetics.  This includes cert validity.
* Via Datadog we're monitoring DNS resolution on www.socallinuxexpo.org and lists.linuxfests.org. Are there other hostnames to monitor? If so, you can see examples of how to add more [here](https://github.com/socallinuxexpo/scale-chef/blob/master/cookbooks/scale_apache/recipes/default.rb#L164-L167).

We're not monitoring whois, but we get email notifications from our registrars.  

does this cover everything @jhoblitt ?

**Comment by irabinovitch** [comment]
@jhoblitt ping?

**Comment by irabinovitch** [comment]
going to call this done. I've set it up to alert #infra in slack as well as email to @hriday, @jaymzh and I.
