### ISSUE TITLE
renew linuxfests.org ssl certificate

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#212]
Our SSL certs expire on 6/23 and need to be renewed or replaced.

**Comment by rgolan** [comment]
My company has been using ssls.com <http://ssls.com/> and getting the 3 year Comodo SSL certs for $5/year. No problems with them.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
We've historically used GoDaddy. I dont have a preference either way, as long as we can either do a multihostname cert or a wildcard cert.

**Comment by rgolan** [comment]
Godaddy will cost more. I think ssls.com <http://ssls.com/> has wildcards for about $85./year.

--
Ron Golan
ron@rgon.us

**Comment by hriday** [comment]
How about the EFF backed site : https://letsencrypt.org

It has an attractive price as well.

**Comment by irabinovitch** [comment]
LetsEncrypt isn't really meant for our use case.  They dont support wildcards or multiple hostnames.  $100~ a year isn't unreasonable for our use.

**Comment by irabinovitch** [comment]
Reviewing the certs we have:

1. www.linuxfests.org (additional hostnames included linuxfests.org, lists.linuxfests.org, mail.linuxfests.org) - expires 6/23
2. www.socallinuxexpo.org (additional host names included are socallinuxexpo.org,wiki.socallinuxexpo.org, reg.socallinuxexpo.org,helpdesk.socallinuxexpo.org).  - expires end of August.
3.  register.linuxfests.org (additional hostnames included are register.texaslinuxfest.org and register.devopsdayssv.com) - expires August 30

**Comment by irabinovitch** [comment]
I'm not going to renew the linuxfests.org cert at this time.  Nothing critical is using it, and we're mid migration/shutdown on most of those services.
