### ISSUE TITLE
Record new welcome message for scale phone line

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#214]
Lets record a new welcome message and menu for the SCALE phone line (877-831-2569).  Our provider Teliax will take most formats, but MP3 or AAC seemed to work best.

**Comment by irabinovitch** [comment]
You can hear the current message 877-831-2569

Current Scripts are

Recording 1: Welcome Message
====
Thank you for calling SCALE and LinuxFests. If you know the extension of the party you wish to reach you may dial it at any time. For non-profit and commercial exhibitor opportunities press 1,  for public relations press 2, for accounting press 3. For general show information press 8, or to send a fax press 9. You may repeat this menu by pressing *.

Recording 2
=====
SCALE 15x, the 15th annual SCALE conference will be held March 2-5, 2017.  Sessions and seminars will take place Thursday March 2 - Sunday March 5th.  Our exhibit hall will be open Friday March 3 - Sunday March 5th.  For more information see our website at www.socallinuxexpo.org

**Comment by nathanhaines** [comment]
Here are some recordings with slightly altered scripts based on the actual recording.

[scale15x-ivr.zip](https://github.com/socallinuxexpo/SCALE-Planning/files/705748/scale15x-ivr.zip)

**Comment by irabinovitch** [comment]
Thanks @nathanhaines
