### ISSUE TITLE
link to call for papers from scale15x home page

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#215]
@rgolan Lets link to call for papers from scale15x home page.

**Comment by rgolan** [comment]
Do you want this link and CFP page to go live now?

**Comment by shyamkapadia** [comment]
Yes please...

On Sat, Jul 2, 2016 at 8:21 PM, Ron Golan <notifications@github.com> wrote:

> Do you want this link and CFP page to go live now?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/socallinuxexpo/SCALE-Planning/issues/215#issuecomment-230133077>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEML4AR_iy2XZf19ty8dODY6O7JYvO9yks5qRyqdgaJpZM4JDxYB>
> .
>



-- 
Regards,
Shyam Kapadia
Speakers Chair
Southern California Linux Expo (SCALE)
http://www.socallinuxexpo.org

**Comment by rgolan** [comment]
I just added the link to the page at http://www.socallinuxexpo.org/scale/15x/ <http://www.socallinuxexpo.org/scale/15x/>

We still don’t have a working redirect from non-www to www for the site.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by rgolan** [comment]
http://socallinuxexpo.org on Firefox gives an Apache Testing 1..2..3.. page.

**Comment by irabinovitch** [comment]
Should be fixed in https://github.com/socallinuxexpo/scale-chef/commit/6828bb8929b95150d5466c121edf1ea52e6b3dde
