### ISSUE TITLE
Updates for SCALE 15x Call for papers

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#216]
The following should be removed from the topic list:

New to SCALE
Hot Applications

And the following should be added:
Open Data
Open Source in Enterprises
Open Source Storage

**Comment by irabinovitch** [comment]
Also lets hide the following options until they're confirmed for SCALE 15x

Apache Bigtop
Beginners Tutorial
Ubucon
Postgres
Puppet

**Comment by irabinovitch** [comment]
New CFP text here: [scale15x.pdf](https://github.com/socallinuxexpo/SCALE-Planning/files/344789/scale15x.pdf)

**Comment by rgolan** [comment]
I have modified the topic list as requested and created a new CFP page at /scale/15x/cfp. 

I noticed that Git on prod says it's ahead of origin/master by 5 commits. I don't know how that is possible and what those commits are. When I just tried to pull my changes on production it created a merge commit. Could you please look into this?

**Comment by irabinovitch** [comment]
Checking.

**Comment by shyamkapadia** [comment]
Noticing a few formatting errors:

1]  These should all be individual bullets

   - Open Source Productivity Applications • Open Source Multimedia and
   Gaming • Tools for Profiling and Performance Tuning
   - Open Source Animation Tools • Open Source Promotion and Adoption:
   Current State

2] A few places there are un-necessary hifens like:

Next Generation - This gives the Free and Open Source community youth *lead-
ers* of tomorrow an
Puppet/Chef/Ansible, Open *Vir- tual Switch (OVS),* Big Data platforms, etc
Embedded - This track covers topics related to Open Source Embedded* hard-
ware* & software.
Developer - This track coves a broad range of topics related to kernel,
file *sys- tem,* and application development.
Open Source Storage - Storage solutions based on Open Source software have
been around for many years now. The maturity of these offerings and
the *contin-
uous innovations* will be the focus of this newly introduced track.
Mentoring - This track presents an opportunity for community leaders and *ex-
perts* from a variety of projects to share the knowledge and experiences
they have gained from their respective projects.


On Sat, Jul 2, 2016 at 8:52 PM, Ron Golan <notifications@github.com> wrote:

> I have modified the topic list as requested and created a new CFP page at
> /scale/15x/cfp.
>
> I noticed that Git on prod says it's ahead of origin/master by 5 commits.
> I don't know how that is possible and what those commits are. When I just
> tried to pull my changes on production it created a merge commit. Could you
> please look into this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/socallinuxexpo/SCALE-Planning/issues/216#issuecomment-230133878>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEML4FQePuOlESvT3j8r66sMaBNsuOQRks5qRzIRgaJpZM4JDxYm>
> .
>



-- 
Regards,
Shyam Kapadia
Speakers Chair
Southern California Linux Expo (SCALE)
http://www.socallinuxexpo.org

**Comment by shyamkapadia** [comment]
One more under Topics of Interest:


   - In-depth Programming/Scripting with Open Source Languages (Examples*
   in- clude* Perl, Ruby, Python, Shell-programming etc.)


On Sat, Jul 2, 2016 at 9:03 PM, Shyam Kapadia <shyamkapadia@gmail.com>
wrote:

> Noticing a few formatting errors:
>
> 1]  These should all be individual bullets
>
>    - Open Source Productivity Applications • Open Source Multimedia and
>    Gaming • Tools for Profiling and Performance Tuning
>    - Open Source Animation Tools • Open Source Promotion and Adoption:
>    Current State
>
> 2] A few places there are un-necessary hifens like:
>
> Next Generation - This gives the Free and Open Source community youth *lead-
> ers* of tomorrow an
> Puppet/Chef/Ansible, Open *Vir- tual Switch (OVS),* Big Data platforms,
> etc
> Embedded - This track covers topics related to Open Source Embedded*
> hard- ware* & software.
> Developer - This track coves a broad range of topics related to kernel,
> file *sys- tem,* and application development.
> Open Source Storage - Storage solutions based on Open Source software have
> been around for many years now. The maturity of these offerings and the *contin-
> uous innovations* will be the focus of this newly introduced track.
> Mentoring - This track presents an opportunity for community leaders and *ex-
> perts* from a variety of projects to share the knowledge and experiences
> they have gained from their respective projects.
>
>
> On Sat, Jul 2, 2016 at 8:52 PM, Ron Golan <notifications@github.com>
> wrote:
>
>> I have modified the topic list as requested and created a new CFP page at
>> /scale/15x/cfp.
>>
>> I noticed that Git on prod says it's ahead of origin/master by 5 commits.
>> I don't know how that is possible and what those commits are. When I just
>> tried to pull my changes on production it created a merge commit. Could you
>> please look into this?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/socallinuxexpo/SCALE-Planning/issues/216#issuecomment-230133878>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AEML4FQePuOlESvT3j8r66sMaBNsuOQRks5qRzIRgaJpZM4JDxYm>
>> .
>>
>
>
>
> --
> Regards,
> Shyam Kapadia
> Speakers Chair
> Southern California Linux Expo (SCALE)
> http://www.socallinuxexpo.org
>



-- 
Regards,
Shyam Kapadia
Speakers Chair
Southern California Linux Expo (SCALE)
http://www.socallinuxexpo.org

**Comment by rgolan** [comment]
I think all those are fixed now. The PDF file is problem for copying and pasting without incorrect styling. A plain text file is better.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
@rgolan the git issues you mentioned earlier are fixed.

**Comment by rgolan** [comment]
Thanks!

**Comment by irabinovitch** [comment]
@rgolan Is it possible to change the logo at the top of the page?

**Comment by rgolan** [comment]
I just changed the default theme to the 15x one. Pages without the 14x in the path will now show the 15x theme.

**Comment by irabinovitch** [comment]
thanks Ron. Closing.
