### ISSUE TITLE
https://lists.linuxfests.org has a bad cert

### ISSUE THREAD

**Issue by leizleiz** [socallinuxexpo/SCALE-Planning#218]
Visiting https://lists.linuxfests.org in several browser + OS combinations all fail with a warning message. e.g. Firefox says:

The owner of lists.linuxfests.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

lists.linuxfests.org uses an invalid security certificate. The certificate is not trusted because it is self-signed. The certificate is only valid for www.socallinuxexpo.org Error code: SEC_ERROR_UNKNOWN_ISSUER

**Comment by irabinovitch** [comment]
Ya our cert there expired. We'll get a new one soon.

**Comment by irabinovitch** [comment]
Replaced.
