### ISSUE TITLE
add postgres back to CFP

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#219]
Postgres has confirmed for 2017, lets unhide their topic on the CFP page. Thanks!

**Comment by irabinovitch** [comment]
@rgolan can we add this one back? Thanks.

**Comment by rgolan** [comment]
I'm away right now but try to do this by tomorrow

**Comment by rgolan** [comment]
PostgreSQL is now available again as a presentation topic.

**Comment by rgolan** [comment]
Closing.
