### ISSUE TITLE
DOD/DON Blocked by Category

### ISSUE THREAD

**Issue by efbatey** [socallinuxexpo/SCALE-Planning#222]
No way with https, http web addresses have never been surveyed by govt contractor, thus have NO category.  Once certs settle / update,  ANYONE with DOD/DON contact may wish to have our websites assessed.  Porn makes it, technology should make it.  SCALE, best budget training in the world .. /Everett - GV - 805-616-2471 / Chat/Skype efbatey

**Comment by irabinovitch** [comment]
Hi Ev, I dont understand the request.

**Comment by irabinovitch** [comment]
@efbatey can you help clarify what we need to do here?

**Comment by irabinovitch** [comment]
@efbatey poke?

**Comment by efbatey** [comment]
USN contractors Blue-something categorize big web sites which are then usually visible on navy.mil.  Until someone persuades these folks to assess and categorize the website, they are declared Blocked-by-Category.  They have no category.  Someone friendly needs to request categorization.

**Comment by irabinovitch** [comment]
I think you're the only person we know in the defense space that works on SCALE as well.

**Comment by irabinovitch** [comment]
Going to close this since theres not much we can do here.  Please re-open if we find a contact who wants to help.
