### ISSUE TITLE
Add hotels to SCALE 15x site

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#223]
Lets add room block info to the website. Reservation links to come soon.

Sheraton Pasadena  - $169/night
https://www.starwoodmeeting.com/events/start.action?id=1608155800&key=AAD6BBD
303 Cordova Street, Pasadena, CA 91101

Hilton Pasadena - $169/night
http://www.hilton.com/en/hi/groups/personalized/P/PASPHHF-SCLE-20170227/index.jhtml?WT.mc_id=POG
168 South Los Robles Avenue, Pasadena, CA 91101

**Comment by irabinovitch** [comment]
Updated linke for the hilton:
http://www.hilton.com/en/hi/groups/personalized/P/PASPHHF-SCLE-20170227/index.jhtml?WT.mc_id=POG

**Comment by rgolan** [comment]
I guess we can add this when we turn on the 15x site. We can put the information in the Venue body or in a sidebar block on that page.

**Comment by lcafiero** [comment]
On a side note, is this something we want to get out to the public in one
shot or piecemeal -- e.g., do we want to post the Hilton link without the
Sheraton or Westin links? Just wondering, because it's something that we
can promote now that there's a sort of lull in the expo schedule.

Larry

**Comment by irabinovitch** [comment]
The links to the 2 hotels we plan to contract are in the ticket. I'm not expecting anything further.

**Comment by irabinovitch** [comment]
@rgolan Thats more or less what i was thinking. Similar to previous years.   When do we want to start work on the new site? Would probably be good sooner rather than later, but not sure when you're back from your travels.

**Comment by irabinovitch** [comment]
@rgolan when might be good to start launching the website?

**Comment by rgolan** [comment]
I can turn it on this weekend.

**Comment by irabinovitch** [comment]
OK. Thanks. Let me know if you need help with anything.

**Comment by rgolan** [comment]
I have added the hotel information to the 15x site but I think the Hilton entry could use more work.

https://www.socallinuxexpo.org/scale/15x/hotel-information

**Comment by rgolan** [comment]
Has anyone reviewed the changes?

**Comment by lcafiero** [comment]
They look OK to me. I don't know if we have anything more on the Hilton.
Ilan?

**Comment by irabinovitch** [comment]
Both hotels are 169.00 /night.
