### ISSUE TITLE
enable sponsor and exhibitor pages

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#225]
Hey @rgolan we have a number of sponsors and exhibitors signed up. Can we start adding them?

**Comment by rgolan** [comment]
Yes, go ahead and add the Sponsor nodes.

**Comment by irabinovitch** [comment]
@rgolan OK. I've added a few sponsors and exhibitors. Anything else need doing to show the links?

**Comment by rgolan** [comment]
The sponsors and exhibitor pages should be working as well as the right sidebar view. Do you mean the sponsor and exhibitor list pages?

**Comment by irabinovitch** [comment]
I see them on the CFP and talk pages, but theres no way to get to there from the home page.  We also historically had some sponsor logos on the home page.  We may just need to add links?

**Comment by irabinovitch** [comment]
Ping re:adding links.

**Comment by rgolan** [comment]
The logos in the right sidebar are working. Maybe you have something blocking them in your browser? I'll turn on the menu items for the list pages.

**Comment by irabinovitch** [comment]
Yes, logos are there now. Just asking about the links in the menu bar. Thanks!

**Comment by irabinovitch** [comment]
@rgolan  Thanks for adding Exhibitors. Looks like we still need to add the sponsors listing somewhere? Thanks!

**Comment by leizleiz** [comment]
BTW, https://www.socallinuxexpo.org/scale/15x links to https://www.socallinuxexpo.org/scale/14x/sponsor/facebook which then has no way to get back to the 15X site.
