### ISSUE TITLE
Missing "Embedded" Topic in CFP search

### ISSUE THREAD

**Issue by ka6sox** [socallinuxexpo/SCALE-Planning#226]
Ability to search for "embedded" topic is missing.

**Comment by rgolan** [comment]
Hi Tom,

I enabled the Embedded topic in the filters on

https://www.socallinuxexpo.org/presentations-filtered <https://www.socallinuxexpo.org/presentations-filtered>

I think that must be the page you’re referring to.

—
Ron Golan
rgolan@superconcentrated.com

**Comment by irabinovitch** [comment]
@ka6sox are you all set here?

**Comment by irabinovitch** [comment]
Closing as we've not heard back and the CFP is now closed.
