### ISSUE TITLE
Banner Ads for Linux New Media Sites

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#228]
@ScislaC, Linux New Media needs ads for the following size to run on their websites:

728x90
300x250

**Comment by irabinovitch** [comment]
@ScislaC do we have anything we can share here?

**Comment by irabinovitch** [comment]
@scislac ping?

**Comment by leizleiz** [comment]
Did this make it? Close?

**Comment by irabinovitch** [comment]
This was not completed, but is no longer needed since SCALE 15x is over.
