### ISSUE TITLE
Linux New Media Ads

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#229]
@ScislaC Our ads on LinuxNewMedia's print publications have the following due dates:

ADMIN Network & Security #37 -- materials due January 25
Linux Pro Magazine/Linux Magazine #196 -- materials due January 11
Raspberry Pi Geek #21 -- materials due December 21

**Comment by irabinovitch** [comment]
@ScislaC just making sure you saw the 12/21 deadline here.

**Comment by ScislaC** [comment]
@irabinovitch Who is the contact on this? I did up an ad earlier today and emailed the two advertising contacts from the RPG website, but haven't heard back (one of them bounced as the account no longer exists).

**Comment by ScislaC** [comment]
@irabinovitch Reached out to Gwen, thank you!

**Comment by irabinovitch** [comment]
Just a reminder that we have a few more deadlines coming up next week.

**Comment by leizleiz** [comment]
Did this make it? Close?

**Comment by irabinovitch** [comment]
Ads were submitted.
