### ISSUE TITLE
Add SCALE 15X webpages for special events

### ISSUE THREAD

**Issue by leizleiz** [socallinuxexpo/SCALE-Planning#230]
We should bring the 15x equivalent of the following webpages online:

https://www.socallinuxexpo.org/scale/14x/events
https://www.socallinuxexpo.org/scale/14x/open-source-legal-training
https://www.socallinuxexpo.org/scale/14x/ubucon-summit
https://www.socallinuxexpo.org/scale/14x/installfest

**Comment by leizleiz** [comment]
@irabinovitch added https://www.socallinuxexpo.org/scale/15x/ubucon-summit and https://www.socallinuxexpo.org/scale/15x/open-source-legal-training, but the latter still links to registration using the old sub domain.

**Comment by irabinovitch** [comment]
Fixed the legal link.

**Comment by irabinovitch** [comment]
@leizleiz  Events page now has content: https://www.socallinuxexpo.org/scale/15x/events

@rgolan can we link to it from somewhere ?

**Comment by rgolan** [comment]
If we can get some content promoted to the front page, we can enable that and then use the content and menu links to link to those items.

**Comment by irabinovitch** [comment]
@rgolan I think this is ready to go?

**Comment by irabinovitch** [comment]
@rgolan can we add links to the special events?
