### ISSUE TITLE
link to hotel info from home page

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#231]
Had a few requests come in for hotel info.  Can we link to this?

http://www.socallinuxexpo.org/scale/15x/hotel-information

**Comment by rgolan** [comment]
I would like to get the real home page up as the default page but I think there is no content on it yet. We just need to tag some content with scale15x and promote to front page. Then the regular menu links will be available. I'll also be able to create some left sidebar blocks if we want to really promote something.

**Comment by irabinovitch** [comment]
@rgolan OK. I can flag some speakers as 'featured' for that block.  In the mean time I'm creating a registration is now open blog post.

**Comment by rgolan** [comment]
Let's try to get this done tomorrow. I'm going out of town on Saturday for a week.

**Comment by irabinovitch** [comment]
@rgolan ok. I'm on a plane for a good chunk of tomorrow, but I'll  try to check in regularly.

**Comment by rgolan** [comment]
I switched over to the dynamic home page and the Registration is Open post is showing now.

**Comment by irabinovitch** [comment]
@rgolan Thanks. Will featured speakers show when I flag them?  I believe we have a number of speakers and sponsors published.  Anything we need to do to get those linked as well?

**Comment by efbatey** [comment]
@irabinovitch  @rgolan  Thanks, now I can send potential guests to Scale15x.

**Comment by irabinovitch** [comment]
@rgolan Happy new year. Can we get those pages linked in the menu bar?
