### ISSUE TITLE
Update SCALE Facebook page for 15X

### ISSUE THREAD

**Issue by leizleiz** [socallinuxexpo/SCALE-Planning#232]
https://www.facebook.com/socallinuxexpo/ still has a banner for SCALE 14X with 14X dates...

**Comment by irabinovitch** [comment]
Waiting on https://github.com/socallinuxexpo/SCALE-Planning/issues/221

**Comment by irabinovitch** [comment]
@ScislaC  do we have anything we can use on FB?

**Comment by irabinovitch** [comment]
Looks like this was done.
