### ISSUE TITLE
scalereg reports return 500 error

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#234]
Hey @leizleiz , Our registration reports page:
returning a 500 error. 

```Server Error (500)
There's been an error. Please report this. Thanks for your patience.

Error: 'Options' object has no attribute 'admin'
URL: /reports/

```

Going directly to the dashboard report seems to work (https://register.socallinuxexpo.org/reports/dashboard/)

**Comment by leizleiz** [comment]
I fixed the reports page, but the other reports it links to aside from the dashboard are all broken still.

**Comment by leizleiz** [comment]
There's still other reporting brokenness as previously mentioned, but we can fix those in a separate issue.
