### ISSUE TITLE
Remove registration link from archived sites' navbars

### ISSUE THREAD

**Issue by leizleiz** [socallinuxexpo/SCALE-Planning#237]
https://www.socallinuxexpo.org/scale/14x/ and older sites still have navbar links to register, which is a bit weird because one cannot register for previous SCALE events. Also, because we changed the registration website's URL this year, the old links no longer navigates to anywhere useful.

**Comment by rgolan** [comment]
I removed the Register links on the 13x and 14x sites. I think 12x is a static site.
