### ISSUE TITLE
add speakers / presentations links to nav bar

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#239]
Lets add speakers / presentations links to the nav bar.

**Comment by rgolan** [comment]
These have been added. Would you prefer they or something else is moved to the top level?

**Comment by irabinovitch** [comment]
Thanks.

**Comment by irabinovitch** [comment]
Thanks. My 0.02 would be to move these to the top level:

- Schedule (when available)
- Speakers 
- Events
- Exhibitors

And leave the rest under information for now.  What do you think? Just seems like we hide a lot under Information right now.

**Comment by irabinovitch** [comment]
@rgolan any thoughts on this?

**Comment by rgolan** [comment]
I did what you suggested.

**Comment by irabinovitch** [comment]
thanks!
