### ISSUE TITLE
blog posts not showing up on home page

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#242]
This is promoted to the front page but isn't showing up there:
http://www.socallinuxexpo.org/blog/scale-14x-diversity-report

Do we have any limits in place? If thats intentional, should we add a link to the blog somewhere on the site?

**Comment by rgolan** [comment]
I selected 15x as the SCALE event for that node. Now it's showing on the front page. We have a filter on the front page that limits content to that which is marked with the 15x SCALE event and promoted to front page.

**Comment by irabinovitch** [comment]
strange pretty sure we'd done that at some point, but as long as it works, appreciate your help.
