### ISSUE TITLE
Update social media links on SCALE 15x pages

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#243]
We have our social media event pages online for 2017, can we update the links in the left hand side bar? Thanks!

https://www.facebook.com/events/724245121061747/ 
http://lanyrd.com/2017/scale15x/
https://plus.google.com/events/c4knqev1n60ld63d596hgm7tjf4 (can you confirm if this loads for you?)

**Comment by rgolan** [comment]
The google+ link works for me. I updated those 3 links on the production site.

**Comment by irabinovitch** [comment]
Thanks. The G+ link was intermittently 404ing for me last night.
