### ISSUE TITLE
Submit SCALE 15x to local event calendars

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#244]
Lets work together to find a list of local event calendars and post SCALE, Ubucon Summit and our other events to it.  Please post here when you identify a site or post to it, so we dont duplicate.

Now celebrating its 15th year, the Southern California Linux Expo SCALE 15X is the largest Linux and Open Source Software show in North America. The four-day event -- from March 2-5, 2017, at the Pasadena Convention Center -- attracts top speakers and exhibitors from all over North America. Sessions and workshops range from beginner tutorials to seminars for experienced system administrators or software developers. In addition, specialty seminars prior to the weekend are conducted by various groups in the Free and Open Source Software community. For more information, or to register, visit https://www.socallinuxexpo.org

Additional Links to include in posts where possible:
https://www.facebook.com/events/724245121061747/

# LA Calendars ($ = not free)
- [x]  [Pasadena Star News](http://events.pasadenastarnews.com/)
- [x]  [Pasadena Weekly](http://www.pasadenaweekly.com/cms/event/edit/)
- [x]  [Pasadena Now](http://www.pasadenanow.com/main/best-events-calendar/)
- [ ]  [Pasadena Journal-$](http://pasadenajournal.com/contact-us/)
- [x]  [Craigslist](https://losangeles.craigslist.org/search/eee)
- [x] [OC Register](http://www.ocregister.com/common/archives/?catID=25048)
- [x] [Discover Los Angeles](http://www.discoverlosangeles.com/what-to-do/events)
- [x] [City of Pasadena](http://www.cityofpasadena.net/accesspasadena.aspx)
- [x] [Visit Pasadena](http://www.visitpasadena.com/events/)
- [x] [EyeSpy LA](http://eyespyla.com/post)
- [ ] [Hidden Los Angeles] - rentanative@gmail.com
- [x] [LA Magazine](http://www.lamag.com/events/category/lasocial/)
- [x] [LA.com](http://events.la.com/) [Site is not live yet 2/9/17]
- [x] [LA Weekly](http://www.laweekly.com/calendar)
- [x] [Experience LA](http://www.experiencela.com/calendar)
- [x] [Yelp](http://www.yelp.com/events/la)
- [x] [EventFul](http://losangeles.eventful.com)
- [x] [Reddit Los Angeles Calendar](https://docs.google.com/spreadsheet/viewform?formkey=dC1Fa3VsUFQwU190d2Yydzk1eXd0OGc6MA#gid=0)
- [x] LA Times (calendar.letters@latimes.com)
- [x] [LAIst.com](http://www.laist.com) (tips@laist.com)
- [x] [SoCalTech.com Calendar](http://www.socaltech.com/calendar/calendar.php)
- [x] [TechZulu Event Calendar](http://techzulu.com/events/) -- events@techzulu.com
- [ ] [TechVenue Los Angeles-$](http://calendars.techvenue.com/cgi-bin/techvenue.pl?CalendarName=Los_Angeles)
- [x] [LA Tech Calendar](http://latechcalendar.com/)
- [x] [SoCalCal](http://www.socalcal.com)
# TV Station Calendars
- [ ] [KNBC](http://events.nbclosangeles.com/)
- [ ] [KTLA](http://ktla.com/community-calendar/#/90028-los-angeles/all/today)
- [ ] [ABC7](http://abc7.com/community/calendar/)
- [ ] [CBS2 / KCAL9](http://events.losangeles.cbslocal.com/)
- [ ] [KTTV](http://www.foxla.com/about-us/7738916-story)
- [ ] [LA18](http://www.la18.tv/calendar/)
- [x] [PBS KCET](http://www.pbssocal.org/arts-life/events/event-submission/)
- [x] KDOC Public Service Announcements - pcorso@kdoc.tv
- [ ] [KPFK](http://www.kpfk.org/index.php/eventcal/calendarsubmissionform-60)
- [ ] [KUCI](http://www.kuci.org/contact.shtml) - See section on PSA requests
- [ ] [KHAY](http://www.khay.com/events/)

Linux Specific
- [x] [LWN](https://lwn.net/Calendar/)
- [ ]  [Linux Journal](http://www.linuxjournal.com/events)
- [ ] [Linux Magazine](http://www.linux-magazine.com/Resources/Event-Calendar)
- [x] [OpenSource.com](https://opensource.com/resources/conferences-and-events-monthly)
- [ ] [Everything SysAdmin](http://everythingsysadmin.com/calendar.html) 
- [x] [Enterprise SysAdmin Calendar](http://blog.fosketts.net/calendar/)
- [x] [Tech Conferences](http://www.techconferences.io/submit)

# Radio Station Calendars
- [ ] [AMP](http://events.amp.cbslocal.com/)
- [ ] [AIR1](http://www.air1.com/events/submit.aspx)
- [ ] [KPFK](http://www.kpfk.org/index.php/eventcal/calendarsubmissionform-60)
- [ ] [KIIS](http://www.kiisfm.com/event_portal/view/calendar/calendar.html?1358369843905) - communitycalendar@kiisfm.com
- [ ] [KMOZART](http://www.kmozart.com/calendars/submit/)
- [ ] [Country 105](http://www.gocountry105.com/calendars/community/submit/)
- [ ] [KKLA](http://www.kkla.com/template3/Forms/CommunityEvents.aspx)
- [ ] [KEARTH](http://events.kearth101.cbslocal.com/)
- [ ] [POWER106](http://www.power106.com/events/community-events)
- [ ] [TheWave](http://events.947thewave.cbslocal.com/)
- [ ] [KCRW](http://events.kcrw.com/)
- [ ] [KROQ](http://events.kroq.cbslocal.com/)
# School Papers with calendars
- [ ] [CSUN Sun Dial](http://sundial.csun.edu/calendar/)
- [ ] [Cal State Long Beach Daily 49er](http://www.daily49er.com/category/news/events/)
- [ ] [CSULA Univ Times](http://www.csulauniversitytimes.com/contact.php)
- [ ] [Cerritos College Talon Marks](http://www.talonmarks.com/calendar/)
- [ ] [Cal Poly Pomona - PolyPost](http://www.thepolypost.com/calendar/)
- [x] [UCLA Daily Bruin](http://dailybruin.com/contact/)
- [ ] [Daily Trojan](http://dailytrojan.com/)

**Comment by qayshp** [comment]
I can start pinging a few of the names on the list to see about getting SCaLE added. I'm assuming we only want to check off a box when the event is posted by the organization. Do we want to keep track of which organizations have been contacted, and by who?

**Comment by irabinovitch** [comment]
@qayshp Thanks ya if you could check them off, or leave comments here that'd be great. Apologies, I had replied by email but it didn't seem to post to the ticket.

**Comment by leizleiz** [comment]
Thanks for all the help. Shall we close this ticket?

**Comment by irabinovitch** [comment]
I'm closing and creating a new ticket for 16x
