### ISSUE TITLE
Dot-org booth for Mozilla?

### ISSUE THREAD

**Issue by dmarti** [socallinuxexpo/SCALE-Planning#245]
Any .org booths still available? Mozilla is interested in doing a booth this year (I can promise some interesting demos, including Tracking Protection in the browser and converting legacy C projects to Rust)

**Comment by hriday** [comment]
Hi Don,

Yes, they are.

Bala.

**Comment by irabinovitch** [comment]
@dmarti happy to have you.  Can you email bala@socallinuxexpo.org or ilan@? Well get you setup.

**Comment by dmarti** [comment]
Sure, I'll share Bala's info with Sandra Persing, manager of developer events. https://mozillians.org/en-US/u/spersing/
