### ISSUE TITLE
ads for lwn.net

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/SCALE-Planning#250]
Dimensions: 300x250 and 728x90 
File Types: GIF, JPG or PNG

**Comment by irabinovitch** [comment]
728x90 is covered by https://www.socallinuxexpo.org/sites/default/files/promo/scale-16x-728x90.png

We just need a 300x250 now.

**Comment by msgeek703** [comment]
Sure, I can do that. Do you have a graphic you specifically want to use?

**Comment by msgeek703** [comment]
300 height by 250 width, or the other way around?
