### ISSUE TITLE
Budget for Secrets Management

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/SCALE-Planning#253]
We sorely need real secrets management. Today secrets are:

* In email
* In git (sometimes public git!)
* In people's heads
* In people's private password managers

They get forgotten/lost/reset/broken a lot.

Here's a first-pass list of stuff we should be managing in a password manager:

* Twitter API key
* SSL keys
* admin password for mailing lists
* SSH keys for automation (the announce stuff you want)
* SSH keys for deployment
* SASL admin password
* Datadog API key
* drupal secrets
* Switch admin passwords
* Root passwords
* Social Media account passwords

The Infra team has a *strong* preference for [Bitwarden](https://bitwarden.com/). It's open-source, making it a good fit for SCALE's principals. It's had several security audits. If we decide we want to one day, we can even run our own server (though I don't see any need to, at least for now). It supports every platform and all major browsers, including Linux and Android, and even has a CLI interface.

Alternatives include [1Password](https://1password.com/) and [LastPass](https://www.lastpass.com/) (with LastPass being the last choice).

This was originally requested (non-urgently) on 8/10/22 on the Chairs mailing list. @irabinovitch requested a list of use-cases which was provided on 8/11 and is reproduced above. However, as we approach SCALE 20X, we'll need time to move stuff into whatever solution, get groups and shared folders all setup with the right permissions, figure out how to manage the whole thing and get the various teams on board.

**Comment by genebean** [comment]
Are there next steps on this people can help with?

**Comment by irabinovitch** [comment]
If you can convince one of the vendors to donate services, we can consider it.  Otherwise we'd need to cut spend somewhere else like staff hotel rooms.

**Comment by genebean** [comment]
How many users would be needed in a paid version? Alternatively, how would you feel about someone like myself hosting the self hosted version of Bitwarden?

**Comment by irabinovitch** [comment]
No idea how many users. I've not gotten a clear answer there.  I'm not opposed to hosting a free self-hosted version, but id guess we want some of the non-free features.

**Comment by jaymzh** [comment]
There are no non-free features. It's all opensource!

Yeah hosting would be great. Lets assume 50+ users (but < 100), which was the target I gave Ilan last year - that  covers all chairs and primary tech folks with room to spare.

As a bitwarden user, I considered hosting it myself as well, but I barely have time to keep our other infra updated.

I know the VP of eng at 1Password and can hit him up to see if they'd donate. Ilan only got back to me on the budget shortage recently, so I haven't acted on either yet. I'd prefer to start there so we're running one less thing.

**Comment by genebean** [comment]
Looks like we can get 1Password for free because of what SCALE is. I'll look at getting this going. 

https://github.com/1Password/1password-teams-open-source

**Comment by jaymzh** [comment]
Brilliant!

**Comment by irabinovitch** [comment]
They previously declined us but happy to have you try.

**Comment by jaymzh** [comment]
> They previously declined us but happy to have you try.

Through that process? Lame.

@genebean - why don't I hit up Pedro. He's actually the CTO, not the VPofEng. I bet he can make this all just go away.

@irabinovitch - if you have some reference to when we got rejected, that'd be helpful

**Comment by genebean** [comment]
Nice. I just started it a few minutes ago... is it worth finishing this path first?

**Comment by jaymzh** [comment]
If we already went through it, and especially if @irabinovitch  has any sort of reference/email/date/something, it's probably worth me chatting with pedro first. Just my take

**Comment by genebean** [comment]
Sure thing. Can I shoot you an invite to the org I just created? I can use the email in your GitHub profile or I'm guessing your linuxfests one is your name at that domain.
Edit: I'm guessing `@phil` in scale slack is you too and that has an email associated with it

**Comment by jaymzh** [comment]
I signed up. Would you mind making me an admin of the org?

**Comment by genebean** [comment]
You both are owners & admins now

**Comment by jaymzh** [comment]
Thanks. Pedro say us being denied was probably a mistake and he'll look into it.

**Comment by genebean** [comment]
That is great news!

**Comment by irabinovitch** [comment]
FYI. Sales reps calling to ask when we plan to convert to paying customers.

**Comment by genebean** [comment]
I got an email too

**Comment by jaymzh** [comment]
ignore them for now. I'm working with Pedro, we'll be setup today or tomorrow

**Comment by jaymzh** [comment]
So best anyone can tell @irabinovitch never actually applied. They can't find any reference to Ilan, SCALE, socallinuxexpo, etc. anywhere. I dug through all the PRs as well and found nothing.

I've filed one here at Pedro's request: https://github.com/1Password/1password-teams-open-source/pull/909

It should get sorted soon.

**Comment by irabinovitch** [comment]
I did indeed apply and spoke with someone who told me we didn't qualify. I
did not file a PR.
If you really want it I can track down their name and email.

**Comment by jaymzh** [comment]
It's fine, they were just trying to find the thing to associate it with. As I said I opened a new one, so we're all good.

**Comment by jaymzh** [comment]
OK we've been approved. You should stop getting mails.

However, @irabinovitch - Pedro would really like to track down what happened and asked me to follow up and provide any information on who you spoke to, when, what their reasons were so they can make sure that all teams are aligned on policy internally.

Thanks

**Comment by irabinovitch** [comment]
Glad to hear we were approved.  Feel free to connect us with email and Ill share what I have avaialble.

**Comment by jaymzh** [comment]
done

**Comment by sarcasticadmin** [comment]
@jaymzh @genebean tech would like to leverage 1password if its available. Where did this end up?

**Comment by genebean** [comment]
It is all setup and ready for use. Hit me up in signal or slack with what email you’d like to use with it and I’ll add you.

**Comment by genebean** [comment]
I think this issue can be marked as resolved now that we have 1Password

**Comment by jaymzh** [comment]
I'm leaving it open until I can talk to all the teams and get them all invites and set up appropriate sharing and stuff. Reaching out in summer isn't very effective, but I plan to do so when I'm back from Texas next week.

**Comment by jaymzh** [comment]
This is mostly sorted - all chairs have what they need. Closing.
